In [21]:
import pandas as pd
df = pd.read_csv('weather_data.csv')
df
#check the type data present in day column
type(df.day[0])
#converted the string data type to date timestamp using parse_dates
df = pd.read_csv('weather_data.csv',parse_dates=['day'])
type(df.day[0])
df
#changed the index to date
df.set_index('day',inplace=True)
df
#change the NAN values to zero with new df
new_df = df.fillna(0)
new_df
#change the NAN values with zero only sepecific column
new_df = df.fillna({
    'temperature':0,
    'windspeed':0,
    'event': 'no event'
})
new_df

#carry forwarded fill means null value filled with previous value vertically
new_df = df.fillna(method='ffill')
new_df

#carry backwarded fill means null value filled with previous value vertically
new_df = df.fillna(method='bfill')
new_df

#carry backwarded fill means null value filled with previous value horizontally using axis
new_df = df.fillna(method='bfill', axis = 'columns')
new_df

#carry forward once using limit = 1
new_df = df.fillna(method='bfill', limit =1)
new_df

#carry forward once using limit = 2
new_df = df.fillna(method='bfill', limit =2)
new_df

#interpolate()--a method which specify the mid values base on previous and later value
new_df = df.interpolate()
new_df

#interpole the value base on time
new_df = df.interpolate(method='time')
new_df

#drop the nan value in one column then delete the row
new_df = df.dropna()
new_df

#drop the nan value in all column then delete the row
new_df = df.dropna(how='all')
new_df

#thresh if threshold value is 1 the drop the row if one value is null
new_df = df.dropna(thresh=1)
new_df

#thresh if threshold value is 2 the drop the row if two value is null
new_df = df.dropna(thresh=2)
new_df

#insert the date range by reindexing
dt = pd.date_range('01-01-2017','01-11-2017')
idx = pd.DatetimeIndex(dt)
df = df.reindex(idx)
df

C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:25: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='ffill')
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:29: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill')
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:33: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill', axis = 'columns')
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:33: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  new_df = df.fillna(method='bfill', axis = 'columns')
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:37: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill', limit =1)
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:41: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  new_df = df.fillna(method='bfill', limit =2)
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:45: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate()
C:\Users\Srinivas Raju\AppData\Local\Temp\ipykernel_1124\3883312109.py:49: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  new_df = df.interpolate(method='time')

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny